=== Smithsonian/dpo-cook/server/schemas/recipe.schema.json
{
    "$id": "https://schemas.3d.si.edu/cook/recipe.json",
    "$schema": "http://json-schema.org/draft-07/schema#",

    "title": "Smithsonian 3D Processing Recipe",

    "definitions": {
        "primitiveValue": {
            "$id": "#primitiveValue",
            "oneOf": [
                {
                    "type": "number"
                },
                {
                    "type": "boolean"
                },
                {
                    "type": "string"
                }
            ]
        },
        "taskParameter": {
            "$id": "#taskParameter",
            "oneOf": [
                {
                    "$ref": "#primitiveValue"
                },
                {
                    "type": "array",
                    "items": {
                        "$ref": "#primitiveValue"
                    }
                },
                {
                    "type": "object",
                    "items": {
                        "$ref": "#primitiveValue"
                    }

                }
            ]
        },
        "recipeParameterMetaSchema": {
            "$id": "#recipeParameterMetaSchema",
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "const": "object"
                },
                "properties": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "object",
                        "oneOf": [
                            {
                                "properties": {
                                    "type": {
                                        "type": "string",
                                        "const": "number"
                                    },
                                    "minimum": {
                                        "type": "number"
                                    },
                                    "maximum": {
                                        "type": "number"
                                    },
                                    "multipleOf": {
                                        "type": "integer"
                                    },
                                    "default": {
                                        "type": "number"
                                    }
                                },
                                "required": [
                                    "type"
                                ]
                            },
                            {
                                "properties": {
                                    "type": {
                                        "type": "string",
                                        "const": "integer"
                                    },
                                    "minimum": {
                                        "type": "integer"
                                    },
                                    "maximum": {
                                        "type": "integer"
                                    },
                                    "multipleOf": {
                                        "type": "integer"
                                    },
                                    "default": {
                                        "type": "integer"
                                    }
                                },
                                "required": [
                                    "type"
                                ]
                            },
                            {
                                "properties": {
                                    "type": {
                                        "type": "string",
                                        "const": "boolean"
                                    },
                                    "default": {
                                        "type": "boolean"
                                    }
                                },
                                "required": [
                                    "type"
                                ]
                            },
                            {
                                "properties": {
                                    "type": {
                                        "type": "string",
                                        "const": "string"
                                    },
                                    "minLength": {
                                        "type": "integer"
                                    },
                                    "maxLength": {
                                        "type": "integer"
                                    },
                                    "default": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "type"
                                ]
                            }
                        ]
                    }
                },
                "required": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "additionalProperties": {
                    "type": "boolean",
                    "const": false
                }
            },
            "required": [
                "type",
                "properties",
                "additionalProperties"
            ]
        },
        "recipeStep": {
            "$id": "#recipeStep",
            "type": "object",
            "properties": {
                "task": {
                    "description": "name of the task to be executed in this step",
                    "type": "string",
                    "minLength": 1
                },
                "description": {
                    "description": "descriptive text for this recipe step",
                    "type": "string",
                    "minLength": 1
                },
                "parameters": {
                    "title": "task parameters",
                    "description": "primitive value or JSONata expression; strings must be put in quotes",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#taskParameter"
                    }
                },
                "pre": {
                    "title": "variables defined before task is started",
                    "description": "primitive value or JSONata expression; strings must be put in quotes",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#taskParameter"
                    }
                },
                "post": {
                    "title": "variables defined after task is done",
                    "description": "primitive value or JSONata expression; strings must be put in quotes",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#taskParameter"
                    }
                },
                "success": {
                    "title": "name of next step to be executed in case of success",
                    "description": "name as string or JSONata expression; string must be put in quotes",
                    "type": "string",
                    "minLength": 1
                },
                "failure": {
                    "title": "name of next step to be executed in case of failure",
                    "description": "name as string or JSONata expression; string must be put in quotes",
                    "type": "string",
                    "minLength": 1
                }
            },
            "required": [
                "task",
                "parameters",
                "success",
                "failure"
            ],
            "additionalProperties": false
        }
    },

    "type": "object",
    "properties": {
        "id": {
            "description": "unique identifier for the recipe",
            "type": "string",
            "minLength": 1
        },
        "name": {
            "description": "recipe name",
            "type": "string",
            "minLength": 1
        },
        "description": {
            "description": "recipe description",
            "type": "string",
            "minLength": 1
        },
        "version": {
            "description": "version of the recipe, must be incremented each time recipe changes",
            "type": "string",
            "minLength": 1
        },
        "parameterSchema": {
            "description": "JSON schema for the recipe's parameters; the schema must be valid against this meta schema",
            "$ref": "#recipeParameterMetaSchema"
        },
        "start": {
            "description": "name of first step to be executed",
            "type": "string",
            "minLength": 1
        },
        "steps": {
            "description": "each recipe step consists of a task to be executed, and next steps in case of success or failure",
            "type": "object",
            "additionalProperties": {
                "$ref": "#recipeStep"
            }
        }
    },
    "required": [
        "id",
        "name",
        "version",
        "parameterSchema",
        "start",
        "steps"
    ],
    "additionalProperties": false
}

=== Smithsonian/dpo-cook/server/recipes/generate-splat.json
{
    "id": "0e8aa2c6-b53e-462b-8237-0c5b6f5442c8",
    "name": "generate-splat",
    "description": "Create gaussian splat from point cloud and camera alignment",
    "version": "1",
    "start": "log",

    "parameterSchema": {
        "type": "object",
        "properties": {
            "sourceImageFolder": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "camerasFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "pointsFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "outputFileBaseName": {
                "type": "string",
                "minLength": 1
            },
            "profile": {
                "type": "string",
                "enum": [
                    "Splat ADC",
                    "Splat MCMC",
                    "Splat3"
                ],
                "default": "Splat3"
            },
            "antiAliasing": {
                "type": "boolean",
                "default": false
            },
            "downscale": {
                "type": "boolean",
                "default": true
            },
            "maxSHDegree": {
                "type": "integer",
                "minimum": 0,
                "maximum": 3,
                "default": 3
            },
            "tool": {
                "type": "string",
                "enum": [
                    "PostShot"
                ],
                "default": "PostShot"
            }
        },
        "required": [
            "sourceImageFolder", "camerasFile", "pointsFile"
        ],
        "advanced": [
        ],
        "additionalProperties": false
    },

    "steps": {
        "log": {
            "task": "Log",
            "description": "Enable logging services",
            "pre": {
                "outputFileBaseName": "$baseName($firstTrue(outputFileBaseName, sourceImageFolder))",
                "baseMeshName": "$firstTrue(outputFileBaseName, sourceImageFolder)",
                "sourceFolderBaseName": "$baseName(sourceImageFolder)"
            },
            "parameters": {
                "logToConsole": true,
                "reportFile": "outputFileBaseName & '-report.json'"
            },
            "success": "'pickup'",
            "failure": "$failure"
        },
        "pickup": {
            "task": "Pickup",
            "description": "Fetch input files from client",
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(pickupPath, $currentDir)",
                "files": {
                    "sourceImageFolder": "sourceImageFolder",
                    "camerasFile": "camerasFile",
					"pointsFile": "pointsFile"
                }
            },
            "success": "'unzip'",
            "failure": "$failure"
        },
        "unzip": {
            "task": "Zip",
            "description": "Unzip image folder",
            "parameters": {
                "inputFile1": "sourceImageFolder",
                "operation": "'unzip'"
            },
            "success": "'delete-standard'",
            "failure": "$failure"
        },
        "delete-standard": {
            "task": "FileOperation",
            "description": "Delete zipped images",
            "parameters": {
                "operation": "'DeleteFile'",
                "name": "sourceImageFolder"
            },
            "success": "'generate-splat'",
            "failure": "$failure"
        },
        "generate-splat": {
            "task": "RadianceField",
            "description": "Create radiance field using pre-aligned cameras",
            "pre": {
                "deliverables": {
                    "meshFile": "baseMeshName & '-' & $lowercase(tool) & '.ply'"
                }
            },
            "parameters": {
                "inputImageFolder": "convertToJpg or preprocess ? sourceFolderConverted : sourceFolderBaseName",
                "camerasFile": "camerasFile",
                "pointsFile": "pointsFile",
                "outputFile": "deliverables.meshFile",
                "profile": "profile",
                "antiAliasing": "antiAliasing",
                "downscale": "downscale",
                "maxSHDegree": "maxSHDegree"
            },
            "success": "'delivery'",
            "failure": "$failure"
        },      
        "delivery": {
            "task": "Delivery",
            "description": "Send result files back to client",
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(deliveryPath, pickupPath, $currentDir)",
                "files": "deliverables"
            },
            "success": "$success",
            "failure": "$failure"
        }
    }
}

=== Smithsonian/dpo-cook/server/recipes/clean.json
{
    "id": "08ac51c5-5fef-47a1-b04b-b02577d6418c",
    "name": "clean",
    "description": "Clean mesh of common issues",
    "version": "1",
    "start": "pickup",

    "parameterSchema": {
        "type": "object",
        "properties": {
            "sourceMeshFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "outputFileBaseName": {
                "type": "string",
                "minLength": 1
            },
            "sourceDiffuseMapFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "sourceMTLFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            }
        },
        "required": [
            "sourceMeshFile"
        ],
        "advanced": [
            
        ],
        "additionalProperties": false
    },

    "steps": {
        "pickup": {
            "task": "Pickup",
            "description": "Fetch input files from client",
            "pre": {
                "baseMeshName": "$baseName($firstTrue(outputFileBaseName, sourceMeshFile))"
            },
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(pickupPath, $currentDir)",
                "files": {
                    "highPolyMeshFile": "sourceMeshFile"
                }
            },
            "success": "'clean-mesh'",
            "failure": "$failure"
        },
        "clean-mesh": {
            "task": "CleanupMesh",
            "description": "Clean up mesh",
            "pre": {
                "deliverables": {
                    "cleanedMeshFile": "baseMeshName & '-cleaned' & '.obj'"
                }
            },
            "parameters": {
                "inputMeshFile": "sourceMeshFile",
                "outputMeshFile": "deliverables.cleanedMeshFile",
                "timeout": 1200
            },
            "success": "'delivery'",
            "failure": "$failure"
        },
        "delivery": {
            "task": "Delivery",
            "description": "Send result files back to client",
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(deliveryPath, pickupPath, $currentDir)",
                "files": "deliverables"
            },
            "success": "$success",
            "failure": "$failure"
        }
    }
}

=== Smithsonian/dpo-cook/server/recipes/inspect-mesh.json
{
    "id": "ee77ee05-d832-4729-9914-18a96939f205",
    "name": "inspect-mesh",
    "description": "Inspects a mesh and returns a report with results",
    "version": "1",
    "start": "log",

    "parameterSchema": {
        "type": "object",
        "properties": {
            "meshFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "inspectionTool": {
                "type": "string",
                "enum": [
                    "Meshlab",
                    "MeshSmith"
                ],
                "default": "Meshlab"
            },
            "pickupPath": {
                "type": "string",
                "minLength": 1
            },
            "deliveryPath": {
                "type": "string",
                "minLength": 1
            },
            "transportMethod": {
                "type": "string",
                "enum": [
                    "none",
                    "local"
                ],
                "default": "none"
            }
        },
        "required": [
            "meshFile"
        ],
        "additionalProperties": false
    },

    "steps": {
        "log": {
            "task": "Log",
            "pre": {
                "baseName": "$baseName(meshFile)",
                "delivery": {
                    "inspectionReport": "baseName & '-inspection.json'"
                }
            },
            "parameters": {
                "logToConsole": true,
                "logFile": "baseName & '-log.txt'",
                "reportFile": "baseName & '-report.json'"
            },
            "success": "'pickup'",
            "failure": "$failure"
        },
        "pickup": {
            "task": "Pickup",
            "description": "Get input files from client",
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(pickupPath, $currentDir)",
                "files": {
                    "meshFile": "meshFile"
                }
            },
            "success": "'inspect'",
            "failure": "$failure"
        },
        "inspect": {
            "task": "InspectMesh",
            "description": "Validate mesh and inspect topology",
            "parameters": {
                "meshFile": "meshFile",
                "reportFile": "delivery.inspectionReport",
                "tool": "inspectionTool"
            },
            "post": {
                "maxRayDistance": "$max($result.inspection.scene.geometry.size) * 0.01"
            },
            "success": "'delivery'",
            "failure": "$failure"
        },
        "delivery": {
            "task": "Delivery",
            "description": "Send result files back to client",
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(deliveryPath, pickupPath, $currentDir)",
                "files": "delivery"
            },
            "success": "$success",
            "failure": "$failure"
        }
    }
}

=== Smithsonian/dpo-cook/server/recipes/photogrammetry.json
{
    "id": "a0af238a-988f-4f3c-bedc-7db0b8220ed5",
    "name": "photogrammetry",
    "description": "Create mesh and texture from image set",
    "version": "1",
    "start": "log",

    "parameterSchema": {
        "type": "object",
        "properties": {
            "sourceImageFolder": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "outputFileBaseName": {
                "type": "string",
                "minLength": 1
            },
            "tool": {
                "type": "string",
                "enum": [
                    "Metashape"
                ],
                "default": "Metashape"
            },
            "scalebarCSV": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "generatePointCloud": {
                "type": "boolean",
                "default": false
            }
        },
        "required": [
            "sourceImageFolder"
        ],
        "advanced": [
            
        ],
        "additionalProperties": false
    },

    "steps": {
        "log": {
            "task": "Log",
            "description": "Enable logging services",
            "pre": {
                "outputFileBaseName": "$baseName($firstTrue(outputFileBaseName, sourceImageFolder))",
                "baseMeshName": "$firstTrue(outputFileBaseName, sourceImageFolder)"
            },
            "parameters": {
                "logToConsole": true,
                "reportFile": "outputFileBaseName & '-report.json'"
            },
            "success": "'pickup'",
            "failure": "$failure"
        },
        "pickup": {
            "task": "Pickup",
            "description": "Fetch input files from client",
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(pickupPath, $currentDir)",
                "files": {
                    "sourceImageFolder": "sourceImageFolder"
                }
            },
            "success": "'unzip'",
            "failure": "$failure"
        },
        "unzip": {
            "task": "Zip",
            "description": "Unzip image folder",
            "pre": {
                "deliverables": {
                    "objZipLow": "scaleToMeters ? baseMeshMapNameLow & '-obj_std.zip' : baseMeshMapNameLow & '-obj.zip'"
                }
            },
            "parameters": {
                "inputFile1": "sourceImageFolder",
                "operation": "'unzip'"
            },
            "success": "'photogrammetry'",
            "failure": "$failure"
        },
        "photogrammetry": {
            "task": "Photogrammetry",
            "description": "Create mesh and texture from image set.",
            "pre": {
                "deliverables": {
                    "meshFile": "baseMeshName & '-' & $lowercase(tool) & '.obj'",
                    "textureFile": "baseMeshName & '-texture-' & '.png'"
                }
            },
            "parameters": {
                "inputImageFolder": "sourceImageFolder",
                "outputFile": "deliverables.meshFile",
                "scalebarFile": "scalebarCSV",
                "generatePointCloud": "generatePointCloud",
                "tool": "tool",
                "timeout": 43200
            },
            "success": "'delivery'",
            "failure": "$failure"
        },
        "delivery": {
            "task": "Delivery",
            "description": "Send result files back to client",
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(deliveryPath, pickupPath, $currentDir)",
                "files": "deliverables"
            },
            "success": "$success",
            "failure": "$failure"
        }
    }
}
